### ISSUE TITLE
Enhance header for mobile

### ISSUE THREAD

**Issue by jfrankl** [microsoft/PlanetaryComputerDataCatalog#216]
I recommend making improvements to the header on mobile. Ideally, it should look like the proposed designs down to 320px width.

### Current site
<img width="318" alt="Screen Shot 2022-01-06 at 10 24 16 AM" src="https://user-images.githubusercontent.com/1809908/148406442-25801bad-8102-434c-9b40-b920b340924f.png">

### Proposed designs

 ![mobile-default](https://user-images.githubusercontent.com/1809908/148406056-a6549e64-2913-4bb2-bcde-66457656315c.png)

![mobile-expanded](https://user-images.githubusercontent.com/1809908/148406060-5d1208d1-d55b-4a8d-886d-9ee226910f6f.png)

**Comment by mmcfarland** [comment]
Resolved in #325
