### ISSUE TITLE
Bounding box for some collections invalid?

### ISSUE THREAD

**Issue by m-mohr** [microsoft/PlanetaryComputerDataCatalog#327]
I think the bounding box for some collections is invalid, the Lat values seem to be swapped or have the wrong sign:

- https://planetarycomputer.microsoft.com/api/stac/v1/collections/alos-fnf-mosaic
- https://planetarycomputer.microsoft.com/api/stac/v1/collections/deltares-floods
- https://planetarycomputer.microsoft.com/api/stac/v1/collections/ecmwf-forecast

More collections could be affected, I stopped at G or so.

**Comment by TomAugspurger** [comment]
Agreed that looks swapped.


- [ ] palsar: https://github.com/stactools-packages/palsar/blob/076700150ecc2999b3aca19761d6a1e21654a302/src/stactools/palsar/constants.py#L25 / https://github.com/stactools-packages/palsar/pull/35
- [ ] Deltares has been temporarily removed, but I'll fix it
- [ ] ecmwf-forecast: https://github.com/stactools-packages/ecmwf-forecast/blob/1c9726e6a4f38e1c15648df6d45a5c8432ce92a9/src/stactools/ecmwf_forecast/stac.py#L158

**Comment by m-mohr** [comment]
fwiw, for STAC Browser a fix is planned so that antimeridian bboxes will work correctly.
Splitting up the bbox only helps partially, as then you still need to provide the union as the first element...
