### ISSUE TITLE
Metadata issues with the cil-gdpcir-cc0 collection

### ISSUE THREAD

**Issue by m-mohr** [microsoft/PlanetaryComputerDataCatalog#347]
The `geoparquet-items` asset in the cil-gdpcir-cc0 collection collection looks weird:
1. uses media_type instead of type
2. has an "extra_fields" which should probably be removed and instead the children should be at the asset level (looks like a PySTAC issue?)

Top-level:
3. Also, the cube:dimensions has lat and lon dimensions, but both have the y axis assigned which sounds wrong to me.
4. The description contains a Table, but CommonMark doesn't support tables

**Comment by TomAugspurger** [comment]
Thanks. The `geoparquet-items` issue also affects the `cil-gdpcir-cc-by` collection.

I did initially mess up the `media_type` / `type` and `extra_assets` field on every collection before fixing them. My fix must have missed these two collections.

The `lat` / `y` axis is indeed a bug from https://github.com/TomAugspurger/xstac/pull/32/files#diff-f8ae444356317c9383e62c6fb03f85370a84d6da649cc30baefd9925f45ae966R116. I'll get that fixed and reingested.
