### ISSUE TITLE
offer to help documentation

### ISSUE THREAD

**Issue by ngam** [microsoft/PlanetaryComputerDataCatalog#351]
as @TomAugspurger and I discussed in closed issues and PRs, I would like to learn and help better document the datasets and their usage. I am currently actively working on my project and spending a significant time on organizing data pipelines, so I thought I would open this issue to offer help and see if we could push for some documentation while at it.

I am particularly concerned with GOES datasets for now, and I can be verbose (I guess good for documenting stuff!) so I don't mind helping write something if I am pointed towards the resources and how to go about things. 

My current "best" workflows:
1. On local disk, simply use netCDF4 alone
2. On abfs (or gs, s3, etc.), use fsspec coupled with h5py

(Note: that netCDF4 seems to outperform h5py by almost an order of magnitude in my local testing, hence the decision to use netcdf4 instead of unifying the approach in 1 --- one could easily use fsspec with h5py for local files too, thus only needing to change a single keyword in the workflow rather than significant portions.)

(Interesting caveat: netCDF4 reads the modified data directly, whereas with h5py one needs to apply the scaling and offsetting manually, so it is actually more work 😅)

**Comment by TomAugspurger** [comment]
Thanks for the offer to help, I appreciate it.

The next step is an overhaul to our example notebooks now that pystac-client 0.5 is out. I have that started at https://github.com/microsoft/PlanetaryComputerExamples/compare/main...feature/sign-inplace?expand=1, and will push it once our containers are updated to use pystac-client 0.5. This includes a discussion of what came up in https://github.com/microsoft/PlanetaryComputerDataCatalog/issues/348#issuecomment-1209886082 around accessing assets from Blob Storage via STAC vs. "directly".

I also have an in-progress document describing our take on "cloud-native geospatial workflows". It'd be good have your thoughts on that so I'll ping you once that's ready.
