### ISSUE TITLE
noaa-mrms-qpe-24h-pass2 reports pass 1 / period 1 in collection

### ISSUE THREAD

**Issue by m-mohr** [microsoft/PlanetaryComputerDataCatalog#390]
https://planetarycomputer.microsoft.com/api/stac/v1/collections/noaa-mrms-qpe-24h-pass2 reports in summaries pass 1 (instead of 2) and period 1 (instead of 24). Looks like wrong parameters have been passed to the stactools package...

**Comment by pjhartzell** [comment]
Yep, that's an error. We'll get that fixed.
